FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY prisma ./prisma
COPY scripts/db-migrate.sh ./scripts/db-migrate.sh
RUN chmod +x ./scripts/db-migrate.sh
RUN npx prisma generate
CMD ["./scripts/db-migrate.sh"]
